# Fly.io config
app = "ai-dashboard-generator-us"   # <-- make sure this matches your Fly app name
primary_region = "iad"              # US (Virginia). You can change to "sea" if preferred.

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
